// Command gen-tool-schemas generates JSON Schemas for a tool package's tools by
// reflecting their argument structs, and writes them as committed Go source
// (ADR-0004). It serves pi's coding toolset (internal/tool/coding). Run via
// `go generate ./...`; CI then fails if the working tree is dirty, which catches
// an arg-struct change that wasn't regenerated.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"reflect"
	"sort"
	"strconv"

	"github.com/unarbos/arbos/internal/tool"
	"github.com/unarbos/arbos/internal/tool/codingspec"
	"github.com/unarbos/arbos/internal/tool/jsonschema"
)

func main() {
	out := flag.String("out", "schemas_gen.go", "output file (relative to the package dir)")
	pkg := flag.String("pkg", "coding", "package name for the generated file")
	specsName := flag.String("specs", "coding", "which spec set to reflect: coding")
	flag.Parse()

	specs := selectSpecs(*specsName)
	type kv struct{ name, schema string }
	rows := make([]kv, 0, len(specs))
	for _, s := range specs {
		schema, err := jsonschema.Reflect(reflect.TypeOf(s.ArgSample))
		if err != nil {
			log.Fatalf("reflect %s: %v", s.Name, err)
		}
		rows = append(rows, kv{name: s.Name, schema: string(schema)})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen-tool-schemas; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	fmt.Fprintf(&b, "import \"encoding/json\"\n\n")
	fmt.Fprintf(&b, "// genSchemas holds the JSON Schema for each tool, reflected from its argument\n")
	fmt.Fprintf(&b, "// struct at generate time so it cannot drift from the handler.\n")
	fmt.Fprintf(&b, "var genSchemas = map[string]json.RawMessage{\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "\t%s: json.RawMessage(`%s`),\n", strconv.Quote(r.name), r.schema)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format generated source: %v\n%s", err, b.String())
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
}

// selectSpecs returns the spec set named on the command line. The spec package
// is standalone (no dependency on generated code), so the generator can import
// it and pick at runtime, keeping one generator usable for any future tool
// package added the same way.
func selectSpecs(name string) []tool.Spec {
	switch name {
	case "coding":
		return codingspec.Specs("")
	default:
		log.Fatalf("unknown -specs %q (want coding)", name)
		return nil
	}
}
